[ssh]
host = "51.158.61.4"
username = "qr_bonus_read"
password = "osdf6585lshi##asd987984#"
remote_bind_host = "127.0.0.1"
remote_bind_port = 6543

[pg]
dbname = "QRBonus"
user = "readonly_user_qrbonus"
password = "asd987984#osdf6585lshi##"